services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      APP_ENV: local
      ENABLE_SWAGGER_UI: "true"
      MONGODB_URI: mongodb://mongodb:27017
    ports:
      - "8080:8080"
    networks:
      - bookstore-network

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init/01-init-bookstore.js:/docker-entrypoint-initdb.d/01-init-bookstore.js:ro
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  mongodb-data:
